<a href="https://colab.research.google.com/github/nykim131/aice/blob/main/associate_%ED%9A%8C%EA%B7%80_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

train_ds1 = pd.read_csv('/content/sample_data/signal_data.csv')

In [13]:
train_ds1

,RID,Time_Departure,Time_Arrival,Distance,Time_Driving,Speed_Per_Hour,Address1,Address2,Weekday,Hour,Day,Signaltype
0,router-84875df7fc-cmkz9-2-9617301-0,19:43:56,19:56:38.537000,3246.0,762.653992,15.322283,경기도,평택시,0,19,27,11.0
1,router-84875df7fc-scxcj-6-13366366-0,12:23:05,12:36:32.620000,3858.0,796.081970,17.446445,경기도,의정부시,4,12,24,17.0
2,router-84875df7fc-52vz8-6-62202063-0,19:10:35,19:29:07.306000,4125.0,1112.468018,13.348698,경기도,광명시,0,19,27,24.0
3,router-84875df7fc-8n4sw-5-6914479-0,11:59:58,12:10:55.999000,3748.0,651.973022,20.695335,경기도,안산시 상록구,0,11,20,19.0
4,router-84875df7fc-8n4sw-7-75115963-0,15:16:53,15:26:52.222000,3153.0,597.419006,18.999730,경기도,성남시 중원구,2,15,29,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,router-84875df7fc-scxcj-7-54933587-0,05:38:47,05:51:42.160000,10807.0,774.018982,50.263884,경기도,평택시,3,5,23,4.0
9996,router-84875df7fc-scxcj-7-68273662-0,16:08:39,16:33:52.275000,6270.0,1511.703003,14.931504,서울특별시,서초구,1,16,28,17.0
9997,router-84875df7fc-b5nxc-5-8232889-0,08:25:22,08:40:26.182000,10484.0,890.312988,42.392283,경기도,안산시 단원구,1,8,21,21.0
9998,router-84875df7fc-52vz8-6-53906748-0,06:49:59,06:55:01.087000,6529.0,300.302002,78.269208,경기도,성남시 분당구,4,6,24,10.0
9999,router-84875df7fc-scxcj-3-24830357-0,23:09:24,23:25:32.432000,7976.0,969.362000,29.621132,서울특별시,마포구,4,23,24,6.0

In [21]:
train_ds1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Distance        9998 non-null   float64
 1   Time_Driving    10000 non-null  float64
 2   Speed_Per_Hour  10000 non-null  float64
 3   Address1        10000 non-null  object
 4   Address2        10000 non-null  object
 5   Weekday         10000 non-null  int64
 6   Hour            10000 non-null  int64
 7   Day             10000 non-null  int64
 8   Signaltype      10000 non-null  float64
dtypes: float64(4), int64(3), object(2)
memory usage: 703.3+ KB

In [20]:
train_ds1.drop('Time_Arrival', axis=1, inplace=True)

In [25]:
train_ds1.isnull().sum()
train_ds1.dropna(inplace=True)

Distance          0
Time_Driving      0
Speed_Per_Hour    0
Address1          0
Address2          0
Weekday           0
Hour              0
Day               0
Signaltype        0
dtype: int64

In [28]:
train_ds1=pd.get_dummies(data=train_ds1,columns=['Address1', 'Address2'])

In [29]:
train_ds1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9998 entries, 0 to 9999
Data columns (total 82 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Distance           9998 non-null   float64
 1   Time_Driving       9998 non-null   float64
 2   Speed_Per_Hour     9998 non-null   float64
 3   Weekday            9998 non-null   int64
 4   Hour               9998 non-null   int64
 5   Day                9998 non-null   int64
 6   Signaltype         9998 non-null   float64
 7   Address1_-         9998 non-null   bool
 8   Address1_경기도       9998 non-null   bool
 9   Address1_서울특별시     9998 non-null   bool
 10  Address1_인천광역시     9998 non-null   bool
 11  Address2_가평군       9998 non-null   bool
 12  Address2_강남구       9998 non-null   bool
 13  Address2_강동구       9998 non-null   bool
 14  Address2_강북구       9998 non-null   bool
 15  Address2_강서구       9998 non-null   bool
 16  Address2_계양구       9998 non-null   bool
 17  Address2_고양시 덕양구   9998 non-null   bool
 18  Address2_고양시 일산동구  9998 non-null   bool
 19  Address2_고양시 일산서구  9998 non-null   bool
 20  Address2_과천시       9998 non-null   bool
 21  Address2_관악구       9998 non-null   bool
 22  Address2_광명시       9998 non-null   bool
 23  Address2_광주시       9998 non-null   bool
 24  Address2_광진구       9998 non-null   bool
 25  Address2_구로구       9998 non-null   bool
 26  Address2_구리시       9998 non-null   bool
 27  Address2_군포시       9998 non-null   bool
 28  Address2_금천구       9998 non-null   bool
 29  Address2_김포시       9998 non-null   bool
 30  Address2_남동구       9998 non-null   bool
 31  Address2_남양주시      9998 non-null   bool
 32  Address2_노원구       9998 non-null   bool
 33  Address2_도봉구       9998 non-null   bool
 34  Address2_동대문구      9998 non-null   bool
 35  Address2_동두천시      9998 non-null   bool
 36  Address2_동작구       9998 non-null   bool
 37  Address2_마포구       9998 non-null   bool
 38  Address2_부천시       9998 non-null   bool
 39  Address2_부평구       9998 non-null   bool
 40  Address2_서구        9998 non-null   bool
 41  Address2_서대문구      9998 non-null   bool
 42  Address2_서초구       9998 non-null   bool
 43  Address2_성남시 분당구   9998 non-null   bool
 44  Address2_성남시 수정구   9998 non-null   bool
 45  Address2_성남시 중원구   9998 non-null   bool
 46  Address2_성동구       9998 non-null   bool
 47  Address2_성북구       9998 non-null   bool
 48  Address2_송파구       9998 non-null   bool
 49  Address2_수원시 권선구   9998 non-null   bool
 50  Address2_수원시 영통구   9998 non-null   bool
 51  Address2_수원시 장안구   9998 non-null   bool
 52  Address2_수원시 팔달구   9998 non-null   bool
 53  Address2_시흥시       9998 non-null   bool
 54  Address2_안산시 단원구   9998 non-null   bool
 55  Address2_안산시 상록구   9998 non-null   bool
 56  Address2_안성시       9998 non-null   bool
 57  Address2_안양시 동안구   9998 non-null   bool
 58  Address2_안양시 만안구   9998 non-null   bool
 59  Address2_양주시       9998 non-null   bool
 60  Address2_양천구       9998 non-null   bool
 61  Address2_양평군       9998 non-null   bool
 62  Address2_여주시       9998 non-null   bool
 63  Address2_연천군       9998 non-null   bool
 64  Address2_영등포구      9998 non-null   bool
 65  Address2_오산시       9998 non-null   bool
 66  Address2_용산구       9998 non-null   bool
 67  Address2_용인시 기흥구   9998 non-null   bool
 68  Address2_용인시 수지구   9998 non-null   bool
 69  Address2_용인시 처인구   9998 non-null   bool
 70  Address2_은평구       9998 non-null   bool
 71  Address2_의왕시       9998 non-null   bool
 72  Address2_의정부시      9998 non-null   bool
 73  Address2_이천시       9998 non-null   bool
 74  Address2_종로구       9998 non-null   bool
 75  Address2_중구        9998 non-null   bool
 76  Address2_중랑구       9998 non-null   bool
 77  Address2_파주시       9998 non-null   bool
 78  Address2_평택시       9998 non-null   bool
 79  Address2_포천시       9998 non-null   bool
 80  Address2_하남시       9998 non-null   bool
 81  Address2_화성시       9998 non-null   bool
dtypes: bool(75), float64(4), int64(3)
memory usage: 1.3 MB

In [30]:
from sklearn.model_selection import train_test_split
X = train_ds1.drop('Time_Driving', axis=1)
y = train_ds1['Time_Driving']

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
X_train.shape, X_valid.shape, y_train.shape, y_valid.shape

((7998, 81), (2000, 81), (7998,), (2000,))

In [34]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
X_train = mms.fit_transform(X_train)
X_valid= mms.transform(X_valid)

In [36]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(max_depth=5,   min_samples_split=3, random_state=120)
dt.fit(X_train, y_train)
print(dt.score(X_valid, y_valid))

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_depth=5,   min_samples_split=3, random_state=120)
rf.fit(X_train, y_train)
print(rf.score(X_valid, y_valid))

0.9007490081075229
0.9657477057386191

In [39]:
pred = rf.predict(X_valid)

from sklearn.metrics import mean_absolute_error

rf_mae = mean_absolute_error(y_valid, pred)

In [40]:
rf_mae

63.80411936924015